users = ['mohamadreza',
         'sharif',
         'puria',
         'masoud',
         'kasra',
         'elham',
         'erfan',
         'alireza',
         'ali',
         'khosro',
         'ashkan',
         'amir',
         'sima']


app_categories = ['Art & Design',
                  'Auto & Vehicles',
                  'Beauty',
                  'Books & Reference',
                  'Business',
                  'Comics',
                  'Communication',
                  'Dating',
                  'Education',
                  'Entertainment',
                  'Events',
                  'Finance',
                  'Food & Drink',
                  'Health & Fitness',
                  'House & Home',
                  'Libraries & Demo',
                  'Lifestyle',
                  'Maps & Navigation',
                  'Medical',
                  'Music & Audio',
                  'News & Magazines',
                  'Parenting',
                  'Personalization',
                  'Photography',
                  'Productivity',
                  'Shopping',
                  'Social',
                  'Sports',
                  'Tools',
                  'Travel & Local',
                  'Video Players; Editors',
                  'Weather']

game_categories = ['Games',
                   'Action',
                   'Adventure',
                   'Arcade',
                   'Board',
                   'Card',
                   'Casino',
                   'Casual',
                   'Educational',
                   'Music',
                   'Puzzle',
                   'Racing',
                   'Role Playing',
                   'Simulation',
                   'Sports',
                   'Strategy',
                   'Trivia',
                   'Word']


tags = ['Badminton',
        'Ball badminton',
        'Biribol',
        'Bossaball',
        'Fistball',
        'Footbag net',
        'Football tennis',
        'Footvolley',
        'Hooverball',
        'Padel',
        'Peteca',
        'Pickleball',
        'Platform tennis',
        'Sepak takraw',
        'Sipa',
        'Throwball',
        'Volleyball',
        'Good',
        'New',
        'Long',
        'great',
        'little',
        'old',
        'right',
        'big',
        'high',
        'different',
        'small',
        'large',
        'early',
        'young',
        'important',
        'few',
        'public',
        'bad',
        'angry',
        'bewildered',
        'clumsy',
        'defeated',
        'embarrassed',
        'fierce',
        'grumpy',
        'helpless',
        'itchy',
        'jealous',
        'lazy',
        'mysterious',
        'nervous',
        'obnoxious',
        'panicky',
        'repulsive',
        'scary',
        'thoughtless',
        'uptight',
        'worried']
